/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package saveq.moduloPago.Interfaz;

import com.google.zxing.WriterException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import saveq.moduloPago.crud.DatosComprobante;
import saveq.moduloPago.Horario.Fecha;
import saveq.moduloPago.Horario.Hora;
import saveq.moduloPago.qr.GenerarQr;

/**
 *
 * @author Micha
 */
public class InterfazMostrarQRComprobantePago extends javax.swing.JFrame {
    Timer actualizar;
    int delay=1000;

    /**
     * Creates new form InterfazMostrarQR
     * @param matricula_datos
     * @throws com.google.zxing.WriterException
     */
    public InterfazMostrarQRComprobantePago(String matricula_datos) throws WriterException {
        
        initComponents();
        panel_nuevoPago.setOpaque(false);
        
        //Generar QR
        GenerarQr generaQR = new GenerarQr();
        DatosComprobante datosqr= new DatosComprobante();
        String informacion=datosqr.obtener_datosQR(matricula_datos);
        BufferedImage imagen = generaQR.crearQR(informacion, 220, 220);
        ImageIcon icono = new ImageIcon(imagen);
        label_qr.setIcon(icono);

        Hora hora=new Hora();
        label_hora1.setText(hora.gethora());
        Fecha fecha=new Fecha();
        label_fecha1.setText(fecha.getfecha());
        this.reloj(1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        background = new javax.swing.JPanel();
        separador = new javax.swing.JSeparator();
        panel_barraSuperior = new javax.swing.JPanel();
        label_hora1 = new javax.swing.JLabel();
        label_fecha1 = new javax.swing.JLabel();
        panel_nuevoPago = new javax.swing.JPanel();
        panel_qr = new javax.swing.JPanel();
        label_qr = new javax.swing.JLabel();
        nuevo_pago = new javax.swing.JButton();
        panel_instrucciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_qrFoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separador.setBackground(new java.awt.Color(72, 203, 182));
        separador.setForeground(new java.awt.Color(72, 203, 182));
        background.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1000, 10));

        panel_barraSuperior.setBackground(new java.awt.Color(0, 0, 0));
        panel_barraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_hora1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        label_hora1.setForeground(new java.awt.Color(255, 255, 255));
        label_hora1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_reloj.png"))); // NOI18N
        label_hora1.setText("  hora");
        panel_barraSuperior.add(label_hora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 140, 50));

        label_fecha1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        label_fecha1.setForeground(new java.awt.Color(255, 255, 255));
        label_fecha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_calendario.png"))); // NOI18N
        label_fecha1.setText("  fecha");
        panel_barraSuperior.add(label_fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 170, 50));

        background.add(panel_barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 50));

        panel_nuevoPago.setBackground(new java.awt.Color(0, 0, 0));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0};
        jPanel4Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        panel_nuevoPago.setLayout(jPanel4Layout);

        panel_qr.setBackground(new java.awt.Color(8, 29, 42));
        panel_qr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 145, 173), 3));

        label_qr.setForeground(new java.awt.Color(255, 255, 255));
        label_qr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_qr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_qrLayout = new javax.swing.GroupLayout(panel_qr);
        panel_qr.setLayout(panel_qrLayout);
        panel_qrLayout.setHorizontalGroup(
            panel_qrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_qrLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(label_qr)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panel_qrLayout.setVerticalGroup(
            panel_qrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_qrLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        panel_nuevoPago.add(panel_qr, gridBagConstraints);

        nuevo_pago.setBackground(new java.awt.Color(76, 203, 182));
        nuevo_pago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nuevo_pago.setForeground(new java.awt.Color(255, 255, 255));
        nuevo_pago.setText("Nuevo Pago");
        nuevo_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_pagoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        panel_nuevoPago.add(nuevo_pago, gridBagConstraints);

        background.add(panel_nuevoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 420, 410));

        panel_instrucciones.setBackground(new java.awt.Color(57, 118, 149));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("¿Qué es esto?");
        panel_instrucciones.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("El QR que se muestra\nen la pantalla \nes su comprobante de pago.");
        panel_instrucciones.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Toma una foto para obtener tu comprobante de pago.");
        panel_instrucciones.add(jLabel4);

        label_qrFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qr_foto.png"))); // NOI18N
        panel_instrucciones.add(label_qrFoto);

        background.add(panel_instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 500, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1030, 550));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevo_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_pagoActionPerformed
        InterfazLeerQRDesdeCamaraWeb qr = new InterfazLeerQRDesdeCamaraWeb();
        qr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nuevo_pagoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_fecha1;
    private javax.swing.JLabel label_hora1;
    private javax.swing.JLabel label_qr;
    private javax.swing.JLabel label_qrFoto;
    private javax.swing.JButton nuevo_pago;
    private javax.swing.JPanel panel_barraSuperior;
    private javax.swing.JPanel panel_instrucciones;
    private javax.swing.JPanel panel_nuevoPago;
    private javax.swing.JPanel panel_qr;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
    
    /* Obtener la hora de entrada para el comprobante */
    public void reloj(int count){
        ActionListener accion = new ActionListener(){
            public void actionPerformed(ActionEvent e){
               Hora hora = new Hora();
               label_hora1.setText(hora.gethora());
//               tabla_entradas.updateUI();
//               tabla_salidas.updateUI();
            }
        };
        actualizar = new Timer(delay,accion);
        actualizar.start();
        
    }
}
