/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package saveq.moduloPago.Interfaz;

import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.ReaderException;
import com.google.zxing.Result;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import saveq.moduloPago.Horario.Fecha;
import saveq.moduloPago.Horario.Hora;
import saveq.moduloPago.Tarifa.Tarifa;
import saveq.moduloPago.crud.SalidaAutomovil;
import saveq.moduloPago.Monedero.ConexionMonedero;




public class InterfazPagar extends javax.swing.JFrame implements Runnable, ThreadFactory {

    private String textmatricula="";
    Timer actualizar;
    int delay=1000;
    private int auxCont=0;
    ConexionMonedero monedero;
    private Executor executor = Executors.newSingleThreadExecutor(this);

    public InterfazPagar(String textmatricula) {
        initComponents();
        Hora hora = new Hora();
        label_hora.setText(hora.gethora());
        Fecha fecha = new Fecha();
        label_fecha.setText(fecha.getfecha());
        this.textmatricula = textmatricula;
        matricula.setText(textmatricula);
        Tarifa classtarifa = new Tarifa();
        tarifa.setText(classtarifa.getTarifa());
        monedero = new ConexionMonedero(classtarifa.getTarifa());
        //cantidad_insertada.updateUI();
        this.reloj(1);
        executor.execute(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panel_barraSuperior = new javax.swing.JPanel();
        label_hora = new javax.swing.JLabel();
        label_fecha = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        panel_qr = new javax.swing.JPanel();
        panel_datosAutomovil = new javax.swing.JPanel();
        matricula = new javax.swing.JLabel();
        texto_insertado = new javax.swing.JLabel();
        texto_matricula = new javax.swing.JLabel();
        cantidad_insertada = new javax.swing.JLabel();
        boton_pago = new javax.swing.JButton();
        texto_pago = new javax.swing.JLabel();
        tarifa = new javax.swing.JLabel();
        panel_instrucciones = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_qrFoto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_barraSuperior.setBackground(new java.awt.Color(0, 0, 0));

        label_hora.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label_hora.setForeground(new java.awt.Color(255, 255, 255));
        label_hora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_reloj.png"))); // NOI18N
        label_hora.setText("hora");

        label_fecha.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label_fecha.setForeground(new java.awt.Color(255, 255, 255));
        label_fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_calendario.png"))); // NOI18N
        label_fecha.setText("fecha");

        javax.swing.GroupLayout panel_barraSuperiorLayout = new javax.swing.GroupLayout(panel_barraSuperior);
        panel_barraSuperior.setLayout(panel_barraSuperiorLayout);
        panel_barraSuperiorLayout.setHorizontalGroup(
            panel_barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_barraSuperiorLayout.createSequentialGroup()
                .addContainerGap(510, Short.MAX_VALUE)
                .addComponent(label_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panel_barraSuperiorLayout.setVerticalGroup(
            panel_barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_barraSuperiorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_hora)
                    .addComponent(label_fecha))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        background.add(panel_barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 50));

        separador.setBackground(new java.awt.Color(72, 203, 182));
        separador.setForeground(new java.awt.Color(72, 203, 182));
        background.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1020, 10));

        panel_qr.setBackground(new java.awt.Color(8, 29, 42));
        panel_qr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 145, 173), 3));

        panel_datosAutomovil.setBackground(new java.awt.Color(8, 29, 42));
        panel_datosAutomovil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 145, 173), 3));
        panel_datosAutomovil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        matricula.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        matricula.setForeground(new java.awt.Color(255, 255, 255));
        matricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        matricula.setText("##-##-##");
        panel_datosAutomovil.add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 342, 30));

        texto_insertado.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        texto_insertado.setForeground(new java.awt.Color(255, 255, 255));
        texto_insertado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        texto_insertado.setText("Cantidad insertada");
        panel_datosAutomovil.add(texto_insertado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 230, -1));

        texto_matricula.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        texto_matricula.setForeground(new java.awt.Color(255, 255, 255));
        texto_matricula.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        texto_matricula.setText("Matricula");
        panel_datosAutomovil.add(texto_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        cantidad_insertada.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cantidad_insertada.setForeground(new java.awt.Color(255, 255, 255));
        cantidad_insertada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidad_insertada.setText("##-##-##");
        panel_datosAutomovil.add(cantidad_insertada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 340, 42));

        boton_pago.setBackground(new java.awt.Color(76, 203, 182));
        boton_pago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boton_pago.setText("Pagar");
        boton_pago.setAlignmentY(0.0F);
        boton_pago.setOpaque(true);
        boton_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_pagoActionPerformed(evt);
            }
        });
        panel_datosAutomovil.add(boton_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 219, 73));

        texto_pago.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        texto_pago.setForeground(new java.awt.Color(255, 255, 255));
        texto_pago.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        texto_pago.setText("Cantidad a pagar");
        panel_datosAutomovil.add(texto_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, -1));

        tarifa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tarifa.setForeground(new java.awt.Color(255, 255, 255));
        tarifa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tarifa.setText("##-##-##");
        panel_datosAutomovil.add(tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 340, 42));

        javax.swing.GroupLayout panel_qrLayout = new javax.swing.GroupLayout(panel_qr);
        panel_qr.setLayout(panel_qrLayout);
        panel_qrLayout.setHorizontalGroup(
            panel_qrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_datosAutomovil, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
        panel_qrLayout.setVerticalGroup(
            panel_qrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_datosAutomovil, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        background.add(panel_qr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 420, 430));

        panel_instrucciones.setBackground(new java.awt.Color(57, 118, 149));
        panel_instrucciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¿Cómo pagar?");
        panel_instrucciones.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 401, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Insertar la cantidad solicitada.");
        panel_instrucciones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 410, 34));
        panel_instrucciones.add(label_qrFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 307, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Paso 2.");
        panel_instrucciones.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 410, 34));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Paso 1.");
        panel_instrucciones.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 410, 34));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tocar en \"Pagar\".");
        panel_instrucciones.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 410, 34));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Colocar la imagen del QR en el lector QR.");
        panel_instrucciones.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 410, 34));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Paso 3.");
        panel_instrucciones.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 410, 34));

        background.add(panel_instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 510, 440));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.png"))); // NOI18N
        background2.setText("jLabel4");
        background.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1020, 550));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_pagoActionPerformed
        
        //Si se ha insertado la cantidad a pagar:
        if(monedero.getSeñal_pago().equals(true)){
            InterfazMostrarQRComprobantePago comprobante;
            try {
                comprobante = new InterfazMostrarQRComprobantePago(this.textmatricula);
                comprobante.setVisible(true); // se muestra el comprobante de pago
            } catch (WriterException ex) {
                Logger.getLogger(InterfazPagar.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
            /* Se marca la matricula como pagada */
            SalidaAutomovil validacion_pago = new SalidaAutomovil();
            validacion_pago.salida_automovil(this.textmatricula);
        }else{
            JOptionPane.showMessageDialog(null,"Inserte la tarifa correspondiente");
        }
    }//GEN-LAST:event_boton_pagoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel background2;
    private javax.swing.JButton boton_pago;
    private javax.swing.JLabel cantidad_insertada;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_fecha;
    private javax.swing.JLabel label_hora;
    private javax.swing.JLabel label_qrFoto;
    private javax.swing.JLabel matricula;
    private javax.swing.JPanel panel_barraSuperior;
    private javax.swing.JPanel panel_datosAutomovil;
    private javax.swing.JPanel panel_instrucciones;
    private javax.swing.JPanel panel_qr;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel tarifa;
    private javax.swing.JLabel texto_insertado;
    private javax.swing.JLabel texto_matricula;
    private javax.swing.JLabel texto_pago;
    // End of variables declaration//GEN-END:variables


//    private void getMatriculaDeQR(Result r) {
//        if (r != null) {
//            String result_string = r.getText();
//            String[] result_parts = result_string.split(",");
//            campo_matricula.setText(result_parts[0]);
//        }
//    }

    /* Obtener la hora de entrada para el comprobante */
    public void reloj(int count){
        ActionListener accion= new ActionListener(){
            public void actionPerformed(ActionEvent e){
               Hora hora=new Hora();
               label_hora.setText(hora.gethora());
               cantidad_insertada.setText(String.valueOf(monedero.getCantidadMonedero()));
//               tabla_entradas.updateUI();
//               tabla_salidas.updateUI();
            }
        };
        actualizar= new Timer(delay,accion);
        actualizar.start();
    }
    
    /* Hilo para recibir el pago */
    @Override
    public void run() {
        do {
            try {
                Thread.sleep(100);
                monedero.iniciar_lecturaMonedero();
                
            } catch (InterruptedException ex) {
                Logger.getLogger(InterfazLeerQRDesdeCamaraWeb.class.getName()).log(Level.SEVERE, null, ex);
            }
        } while (true);
    }

    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "Mi hilo");
        t.setDaemon(true);
        return t;
    }
}
